version: 2
updates:
  # Keep GitHub Actions workflows up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Keep Gradle build dependencies and libs.versions.toml up to date
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
